# Generated by Django 2.1.7 on 2021-01-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_userprofile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accessToken',
            field=models.TextField(null=True),
        ),
    ]
