# Generated by Django 2.1.7 on 2020-10-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0012_auto_20180501_0436'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'submission_tag',
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='tags',
            field=models.ManyToManyField(to='submission.SubmissionTag'),
        ),
    ]
