# Generated by Django 2.2.5 on 2020-11-27 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0010_auto_20190326_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='show_case',
            field=models.BooleanField(default=True),
        ),
    ]
