# Generated by Django 2.2.5 on 2021-01-18 03:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import utils.shortcuts


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SFSubmission',
            fields=[
                ('id', models.TextField(db_index=True, default=utils.shortcuts.rand_str, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField(db_index=True)),
                ('username', models.TextField()),
                ('code', models.TextField()),
                ('result', models.IntegerField(db_index=True, default=6)),
                ('info', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('language', models.TextField()),
            ],
            options={
                'db_table': 'SFSubmission',
                'ordering': ('-create_time',),
            },
        ),
    ]
