# Generated by Django 2.2.5 on 2021-01-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SF_submission', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sfsubmission',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sfsubmission',
            name='username',
        ),
        migrations.AlterField(
            model_name='sfsubmission',
            name='user_id',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
