# Generated by Django 2.2.5 on 2021-01-18 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SF_submission', '0002_auto_20210118_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfsubmission',
            name='test_case',
            field=models.TextField(default=''),
        ),
    ]
