# Generated by Django 2.2.5 on 2021-01-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SF_submission', '0003_sfsubmission_test_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sfsubmission',
            name='code',
            field=models.TextField(default=''),
        ),
    ]
