# Generated by Django 2.2.5 on 2021-01-18 03:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SF_submission', '0004_auto_20210118_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfsubmission',
            name='statistic_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
