# Generated by Django 2.2.5 on 2021-01-18 09:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SF_submission', '0005_sfsubmission_statistic_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sfsubmission',
            name='test_case',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
