# Generated by Django 2.2.5 on 2021-01-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SF_submission', '0006_auto_20210118_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfsubmission',
            name='output',
            field=models.TextField(default=''),
        ),
    ]
