# Generated by Django 2.2.5 on 2021-01-18 09:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SF_submission', '0007_sfsubmission_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sfsubmission',
            name='output',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
