# Generated by Django 2.1.7 on 2020-10-18 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0015_problem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='status',
        ),
    ]
